apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  MONGO_USERNAME: {{ .Values.secrets.mongoUser }}
  MONGO_PASSWORD: {{ .Values.secrets.mongoPassword }}
  MONGO_DB: {{ .Values.secrets.mongoDB }}